name: analize code, security and build an image

on: 
  push:
    branches: ["main"]

# set permissions
permissions:
  contents: read

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Clone the repository and set the branch
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set Python path environment variable
        run: echo "PYTHONPATH=${{ runner.workspace }}" >> $GITHUB_ENV

      - name: Analysing the code with pylint
        run: |
          pylint src/

      - name: execute the test case and code coverage
        run: |
          pytest --cov=src/test/unittests --cov-report term-missing --cov-fail-under=${{vars.MINIMUN_COVERAGE}}
          pytest --html=pytest_report/report.html
          coverage html
        # run: echo build and image of the tests
  # build:
  #   needs: code_analysis
  #   runs-on: ubuntu-latest
  #   environment: dev
  #   steps:
  #     - name: 'Checkout GitHub Action'
  #       uses: actions/checkout@v3
  
  #     - name: Docker Login
  #     # You may pin to the exact commit or the version.
  #     # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         username: ${{ secrets.DOCKER_HUB_USER }}
  #         # Password or personal access token used to log against the Docker registry
  #         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
  #     - name: Build and push Docker images
  #         # You may pin to the exact commit or the version.
  #         # uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
  #       uses: docker/build-push-action@v5.0.0
  #       with:
  #         context: .
  #         push: true
  #         tags: roretar/py-blocks:${{ github.run_number }}
  #     - name: finish
  #       run: |
  #         echo done
  build:
    needs: code_analysis
    runs-on: ubuntu-latest
    steps:
      - run: echo build and image of the tests
    
  deploy-server-on-googlecloud:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy server to googlecloud
      
      
  deploy-server-on-AWS:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo deploy server to AWS
          
  # deploy-server-on-azure:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo deploy server to azzure
  #     - name: Deploy to Azure Web App
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: apidockerimage
  #         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #         images: 'roretar/py-blocks:${{ github.run_number }}'
