name: Run test cases / test cases runners
env: 
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  execute_test_cases:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Clone the repository and set the branch
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3

      - name: Deploy Selenium Grid containers
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
      
      - name: Execute Test Cases
        run: |
          export PYTHONPATH=$PWD
          pip install -r requirements.txt
          docker container ls
          python src/test/gui_tests/create_board.py
      
      - name: Generate The artifacts report
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: report.html

      - name: Send report to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          status: ${{job.status}}
          steps: ${{ toJson(steps) }}
          channel: '#genetal'
        if: always()
