name: Run the smoke tests
env: 
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  build_the_environment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}

  execute_test_cases:
    runs-on: ubuntu-latest

    needs: build_the_environment
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}

      - run: |
          echo "running test cases"
          echo "execution finished successfully, building report"
          echo "test report of smoke testing" > report.html
  
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: report.html

      - name: Send Slack Notification
        uses: keithalpichi/slack-action@x.y.z
        with:
          template: plain2
